import { useEffect, useState } from 'react';
import api, { apiErrorMessage } from '../../api/client';
import { ErrorBanner, Loader } from '../../components/common/UI';

export default function Competitions() {
  const [items, setItems] = useState([]);
  const [form, setForm] = useState({ name: '', description: '', date: '', venue: '', status: 'draft' });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  function load() { api.get('/admin/competitions').then((res) => setItems(res.data)).catch((err) => setError(apiErrorMessage(err))).finally(() => setLoading(false)); }
  useEffect(load, []);
  async function submit(event) { event.preventDefault(); setError(''); try { await api.post('/admin/competitions', form); setForm({ name: '', description: '', date: '', venue: '', status: 'draft' }); load(); } catch (err) { setError(apiErrorMessage(err)); } }
  if (loading) return <Loader label="Loading competitions…" />;
  return <section className="space-y-6"><header><p className="text-xs font-semibold uppercase tracking-wider text-brand-600">Competition setup</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Create a competition</h1><p className="mt-1 text-sm text-slate-500">Create the event, then configure its three rounds from Round Settings.</p></header>{error && <ErrorBanner message={error} />}<div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_1.4fr]"><form onSubmit={submit} className="card space-y-4 p-6"><input className="input" placeholder="Competition name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><textarea className="input min-h-24" placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><input className="input" type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /><input className="input" placeholder="Venue" value={form.venue} onChange={(e) => setForm({ ...form, venue: e.target.value })} /><select className="input" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="draft">Draft</option><option value="published">Published</option></select><button className="btn-primary">Create competition</button></form><div className="card overflow-hidden p-0"><div className="border-b border-slate-100 px-5 py-4 font-semibold text-slate-800">Competition history</div>{items.length === 0 ? <p className="p-5 text-sm text-slate-500">No competitions created yet.</p> : <div className="divide-y divide-slate-100">{items.map((item) => <div key={item._id} className="px-5 py-4"><div className="flex items-center justify-between gap-3"><p className="font-medium text-slate-800">{item.name}</p><span className="badge bg-slate-100 text-slate-600">{item.status}</span></div><p className="mt-1 text-sm text-slate-500">{item.venue || 'Venue not set'}{item.date ? ` · ${new Date(item.date).toLocaleDateString()}` : ''}</p></div>)}</div>}</div></div></section>;
}
