import { useEffect, useState } from 'react';
import api, { apiErrorMessage } from '../../api/client';
import { ErrorBanner, Loader } from '../../components/common/UI';

export default function Leaderboard() {
  const [type, setType] = useState('mcq');
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { setData(null); setError(''); api.get(`/public/leaderboard/${type}`).then((res) => setData(res.data)).catch((err) => setError(apiErrorMessage(err, 'Results have not been published yet.'))); }, [type]);
  return <div className="min-h-screen bg-slate-50 px-4 py-10"><div className="mx-auto max-w-3xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-brand-600">Published results</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Leaderboard</h1></div><select className="input w-auto" value={type} onChange={(e) => setType(e.target.value)}><option value="mcq">MCQ Competition</option><option value="prompt_rush">Prompt Rush</option></select></header>{error && <div className="mt-6"><ErrorBanner message={error} /></div>}{!data && !error ? <Loader label="Loading published results…" /> : data && <section className="card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-800">{data.competition}</h2><p className="text-xs text-slate-500">Official published standings</p></div><div className="divide-y divide-slate-100">{data.items.map((item) => <div key={`${item.rank}-${item.rollNumber}`} className="flex items-center gap-4 px-5 py-4"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-100 text-sm font-bold text-slate-600">{item.rank}</span><div className="min-w-0 flex-1"><p className="font-medium text-slate-800">{item.student}</p><p className="text-xs text-slate-500">{item.rollNumber}{item.department ? ` · ${item.department}` : ''}</p></div><span className="font-mono font-semibold text-brand-700">{Number(item.score).toFixed(1)} / {item.maxScore}</span></div>)}{data.items.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No final results are available.</p>}</div></section>}</div></div>;
}
